name: "Deploy to EC2"

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd ~/tcp-http-server
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh ${{ github.event.workflow_run.head_sha }}

  email-success:
    if: ${{ always() && needs.deploy.result == 'success' }}
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Email
        env:
          RESEND_API_KEY: ${{ secrets.SMTP_PASSWORD }}
          DEPLOY_NOTIFY_EMAIL: ${{ secrets.DEPLOY_NOTIFY_EMAIL }}
        run: |
          DEPLOY_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          COMMIT_URL="${REPO_URL}/commit/${{ github.event.workflow_run.head_sha }}"
          RUN_URL="${REPO_URL}/actions/runs/${{ github.event.workflow_run.id }}"

          curl -sS https://api.resend.com/emails \
            -H "Authorization: Bearer ${RESEND_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{
              "from": "deploy@shazimrahman.dev",
              "to": ["'"${DEPLOY_NOTIFY_EMAIL}"'"],
              "subject": "[tcp-http-server] 🚀 DEPLOY SUCCEEDED",
              "text": "Deployment succeeded.\n\nRepository:\n'"${REPO_URL}"'\n\nCommit:\n'"${COMMIT_URL}"'\n\nActor: ${{ github.event.workflow_run.actor.login }}\nDeploy Time: '"${DEPLOY_TIME}"'\n\nLive Server:\nhttps://httpdemo.shazimrahman.dev\n\nWorkflow Run:\n'"${RUN_URL}"'"
            }'

  email-failure:
    if: ${{ always() && needs.deploy.result == 'failure' }}
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Email
        env:
          RESEND_API_KEY: ${{ secrets.SMTP_PASSWORD }}
          DEPLOY_NOTIFY_EMAIL: ${{ secrets.DEPLOY_NOTIFY_EMAIL }}
        run: |
          DEPLOY_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          COMMIT_URL="${REPO_URL}/commit/${{ github.event.workflow_run.head_sha }}"
          RUN_URL="${REPO_URL}/actions/runs/${{ github.event.workflow_run.id }}"

          curl -sS https://api.resend.com/emails \
            -H "Authorization: Bearer ${RESEND_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{
              "from": "deploy@shazimrahman.dev",
              "to": ["'"${DEPLOY_NOTIFY_EMAIL}"'"],
              "subject": "[tcp-http-server] ❌ DEPLOY FAILED",
              "text": "Deployment failed.\n\nRepository:\n'"${REPO_URL}"'\n\nCommit:\n'"${COMMIT_URL}"'\n\nActor: ${{ github.event.workflow_run.actor.login }}\nDeploy Time: '"${DEPLOY_TIME}"'\n\nLive Server:\nhttps://httpdemo.shazimrahman.dev\n\nWorkflow Run:\n'"${RUN_URL}"'"
            }'
